CREATE TABLE IF NOT EXISTS contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_type VARCHAR(20) NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    plan VARCHAR(120),
    preferred_date VARCHAR(50),
    contact_method VARCHAR(50),
    request_types VARCHAR(255),
    message VARCHAR(4000) NOT NULL,
    english_page BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);
